### ISSUE TITLE
arcitecture visio

### ISSUE THREAD

**Issue by maciejgajownik** [MicrosoftDocs/architecture-center.pl-pl#2]
there is wrong visio file linked for this architecture

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: be033e7f-d78f-f63f-c9b5-f08130315704
* Version Independent ID: d66f5650-fffb-79a6-ee59-40eaad06cd4f
* Content: [Aplikacja n-warstwowa w wielu regionach - Azure Architecture Center](https://docs.microsoft.com/pl-pl/azure/architecture/reference-architectures/n-tier/multi-region-sql-server#related-resources)
* Content Source: [docs/reference-architectures/n-tier/multi-region-sql-server.md](https://github.com/microsoftdocs/architecture-center.pl-pl/blob/live/docs/reference-architectures/n-tier/multi-region-sql-server.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by srvbpigh** [comment]
Hello, @maciejgajownik
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by maciejgajownik** [comment]
IT is ok :)

pon., 8 cze 2020, 12:41 użytkownik srvbpigh <notifications@github.com>
napisał:

**Comment by srvbpigh** [comment]
Hello, @maciejgajownik, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/architecture-center/issues/2170. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
